// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTask struct {
	TaskID          int     `json:"task_id"`
	TaskTitle       string  `json:"task_title"`
	TaskExplanation *string `json:"task_explanation,omitempty"`
	TaskLimit       string  `json:"task_limit"`
	TaskPriority    int     `json:"task_priority"`
	TaskStatus      string  `json:"task_status"`
	UserID          int     `json:"user_id"`
	TaskLabel       int     `json:"task_label"`
}

type Task struct {
	TaskID          int     `json:"task_id"`
	TaskTitle       string  `json:"task_title"`
	TaskExplanation *string `json:"task_explanation,omitempty"`
	TaskLimit       string  `json:"task_limit"`
	TaskPriority    int     `json:"task_priority"`
	TaskStatus      string  `json:"task_status"`
	UserID          int     `json:"user_id"`
	TaskLabel       int     `json:"task_label"`
}
